name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [ master, release* ]
  pull_request_target:
    branches: [ master, release* ]
  workflow_dispatch:

jobs:
  run-build-prod:
    name: Run production build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup node environment
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 20
          check-latest: true
          cache: npm

      - name: Install Node.js dependencies
        run: npm ci --no-audit

      - name: Run a production build
        env:
          JELLYFIN_VERSION: ${{ github.event.pull_request.head.sha || github.sha }}
        run: npm run build:production

      - name: Update config.json for testing
        run: |
          jq '.multiserver=true | .servers=["https://demo.jellyfin.org/unstable"]' dist/config.json > dist/config.tmp.json
          mv dist/config.tmp.json dist/config.json

      - name: Upload artifact
        uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097 # v4.4.2
        with:
          name: jellyfin-web__prod
          path: dist

  publish:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'jellyfin/jellyfin-web' }}
    needs:
      - run-build-prod
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Add comment
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          message: |
            ## Cloudflare Pages deployment

            | **Latest commit** | <code>${{ github.event.pull_request.head.sha || github.sha }}</code> |
            |-------------------|:-:|
            | **Status**        | 🔄 Deploying... |
            | **Preview URL**   | Not available |
            | **Type**          | 🔀 Preview |
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: CFPages-deployment
          mode: recreate

      - name: Download workflow artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: jellyfin-web__prod
          path: dist

      - name: Publish to Cloudflare
        id: cf
        uses: cloudflare/wrangler-action@9681c2997648301493e78cacbfb790a9f19c833f # v3.9.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=jellyfin-web --branch=${{
                  (github.event_name != 'pull_request_target' || github.event.pull_request.head.repo.full_name == github.repository)
                  && (github.event.pull_request.head.ref || github.ref_name)
                  || format('{0}/{1}', github.event.pull_request.head.repo.full_name, github.event.pull_request.head.ref)
                }} --commit-hash=${{ github.event.pull_request.head.sha || github.sha }}

      - name: Update status comment (Success)
        if: ${{ github.event_name == 'pull_request_target' && success() }}
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          message: |
            ## Cloudflare Pages deployment

            | **Latest commit** | <code>${{ github.event.pull_request.head.sha || github.sha }}</code> |
            |-------------------|:-:|
            | **Status**        | ✅ Deployed! |
            | **Preview URL**   | ${{ steps.cf.outputs.deployment-url != '' && steps.cf.outputs.deployment-url || 'Not available' }} |
            | **Type**          | 🔀 Preview |
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: CFPages-deployment
          mode: recreate

      - name: Update status comment (Failure)
        if: ${{ github.event_name == 'pull_request_target' && failure() }}
        uses: thollander/actions-comment-pull-request@fabd468d3a1a0b97feee5f6b9e499eab0dd903f6 # v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
          message: |
            ## Cloudflare Pages deployment

            | **Latest commit** | <code>${{ github.event.pull_request.head.sha || github.sha }}</code> |
            |-------------------|:-:|
            | **Status**        | ❌ Failure. Check workflow logs for details |
            | **Preview URL**   | Not available |
            | **Type**          | 🔀 Preview |
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: CFPages-deployment
          mode: recreate
